version: '2'
services:
  emailrelay-in:
    build: ./Dockerfiles/emailrelay-in
    ports:
      - 587:587
    expose:
      - 587
    hostname: emailrelay-in
    volumes:
      - ERSpoolVolume:/var/spool/emailrelay
    depends_on:
      - emailrelay-out
    networks:
      - ernet

  emailrelay-out:
    image: dcagatay/emailrelay
    ports:
      - ${ER_OUT_PORTNO}
    networks:
      - ernet
    extra_hosts:
      - "${EXT_MAIL_SERVER}:${EXT_MAIL_SERVER_IP}"
    volumes:
      - ERDataVolume:/var/spool/emailrelay
    command:
      - --log 
      - --poll 
      - "0"
      - --forward-to 
      - ${EXT_MAIL_SERVER}:${EXT_MAIL_SERVER_PORT} 
      - --forward
      - --client-tls
      - --tls-config=1
      - --log-time
      - --port
      - "${ER_OUT_PORTNO}"  
      - --filter
      - net:emailrelay-parser:1235 
      - --filter-timeout
      - "70"
      - --remote-clients

  emailrelay-resubmit:
    build: ./Dockerfiles/resubmit
    volumes_from:
      - emailrelay-in
    networks:
      - ernet
 
  emailrelay-parser:
    build: ./Dockerfiles/parser
    ports: 
      - 1235:1235
    hostname: parser
    networks:
      - ernet
      - esnet
    volumes:
      - ImagesVolume:/images
    volumes_from:
      - emailrelay-out

  images-web:
    build: ./Dockerfiles/images
    ports:
      - 80:80
    hostname: images
    networks:
      - ernet
    volumes_from:
      - emailrelay-parser

  tika-parser:
    build: ./Dockerfiles/tika
    ports:
      - 9998:9998
    hostname: tika
    networks:
      - ernet

  elasticsearch:
    build: ./Dockerfiles/elasticsearch
    ports:
      - 9200:9200
    hostname: elasticsearch
    networks:
      - esnet
      - ernet
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2048m
    volumes:
      - ESDataVolume:/usr/share/elasticsearch/data
      - ./Dockerfiles/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    build: ./Dockerfiles/kibana
    ports:
      - 5601:5601
    hostname: kibana
    depends_on:
      - elasticsearch
    networks:
      - esnet
    volumes:
      - ./Dockerfiles/kibana/config/:/usr/share/kibana/config

  image-parser:
    image: buildpack-deps:bullseye
    build: ./Dockerfiles/ocr
    networks:
      - ernet
volumes:
  ERSpoolVolume:
  ERDataVolume:
  ESDataVolume:
  ImagesVolume:
networks:
  ernet:
  esnet:
